CREATE TABLE IF NOT EXISTS `CLIENT CONTACT` (
	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`join date` VARCHAR(50) NULL DEFAULT NULL,
	`phone` VARCHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`username` VARCHAR(50) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	`rating` INTEGER(50) NULL DEFAULT NULL,
	`blocked` BOOLEAN NULL DEFAULT NULL,
	PRIMARY KEY (`pk`),
	FOREIGN KEY (`billing`) REFERENCES CLIENT BILLING(`pk`)
);


CREATE TABLE IF NOT EXISTS `DRIVER CONTACT` (
	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`join date` VARCHAR(50) NULL DEFAULT NULL,
	`phone` VARCHAR(50) NULL DEFAULT NULL,
	`address` VARCHAR(50) NULL DEFAULT NULL,
	`rating` INTEGER NOT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	 PRIMARY KEY (`pk`),
	 FOREIGN KEY (`payroll`) REFERENCES CLIENT BILLING(`pk`)
);

CREATE TABLE IF NOT EXISTS `RIDES` (
	`pk` INTEGER NOT NULL AUTO_INCREMENT,
	`date` VARCHAR(50) NULL DEFAULT NULL,
	`distance` INTEGER NOT NULL AUTO_INCREMENT,
	`trip Cost` INTEGER NOT NULL AUTO_INCREMENT,
	FOREIGN KEY (`dispute`) REFERENCES DISPUTES(`pk`),
	FOREIGN KEY (`client`) REFERENCES CLIENT CONTACT(`pk`),
	FOREIGN KEY (`pool1`) REFERENCES CLIENT CONTACT(`pk`),
	FOREIGN KEY (`pool2`) REFERENCES CLIENT CONTACT(`pk`),
	FOREIGN KEY (`driver`) REFERENCES DRIVER CONTACT(`pk`),
);

CREATE TABLE IF NOT EXISTS `DISPUTES` (
	`pk` INTEGER NOT NULL AUTO_INCREMENT,
	`filing date` VARCHAR(50) NULL DEFAULT NULL,
	`resolved` BOOLEAN NULL DEFAULT NULL,
	FOREIGN KEY (`ride`) REFERENCES RIDES(`pk`),
	PRIMARY KEY (`pk`)
);

CREATE TABLE IF NOT EXISTS `CLIENT BILLING` (
	`pk` INTEGER NOT NULL AUTO_INCREMENT,
	`address` VARCHAR(50) NULL DEFAULT NULL,
	`Acct Info` VARCHAR(50) NULL DEFAULT NULL,
	FOREIGN KEY (`client`) REFERENCES CLIENT CONTACT(`pk`),
	PRIMARY KEY (`pk`)
);

CREATE TABLE IF NOT EXISTS `DRIVER PAYMENT` (
	`pk` INTEGER NOT NULL AUTO_INCREMENT,
	`Acct Info` VARCHAR(50) NULL DEFAULT NULL,
	`Current Pay Period` VARCHAR(50) NULL DEFAULT NULL,
	`Total Gross` INTEGER NOT NULL AUTO_INCREMENT,
	`Total Net` INTEGER NOT NULL AUTO_INCREMENT,
	FOREIGN KEY (`dirver`) REFERENCES DRIVER CONTACT(`pk`),
	PRIMARY KEY (`pk`)
);

