-- CREATE TABLE `ClientContact` (
-- 	`PK` BINARY NOT NULL,
-- 	`Name` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Join Date` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Phone` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Email` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Rating` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Blocked` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Billing` BINARY NOT NULL AUTO_INCREMENT,
-- 	PRIMARY KEY (`PK`)
-- );

-- CREATE TABLE `DriverContact` (
-- 	`PK` BINARY NOT NULL,
-- 	`Name` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Join Date` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Phone` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Email` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Payroll` BINARY NOT NULL,
-- 	`Address` BINARY NOT NULL,
-- 	`Rating` BINARY NOT NULL,
-- 	PRIMARY KEY (`PK`)
-- );

CREATE TABLE `Rides` (
	`PK` BINARY NOT NULL,
	`Date` BINARY NOT NULL,
	`Distance` BINARY NOT NULL,
	`Trip Cost` BINARY NOT NULL,
	`Dispute` BINARY NOT NULL,
	`Client` BINARY NOT NULL,
	`Pool1` BINARY NOT NULL,
	`Pool2` BINARY NOT NULL,
	`Driver` BINARY NOT NULL
);

-- CREATE TABLE `Disputes` (
-- 	`PK` BINARY NOT NULL,
-- 	`Ride` BINARY NOT NULL,
-- 	`Driver` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Client` BINARY NOT NULL,
-- 	`Resolved` BINARY NOT NULL,
-- 	PRIMARY KEY (`PK`)
-- );

-- CREATE TABLE `ClientBilling` (
-- 	`PK` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Billing Address` BINARY NOT NULL,
-- 	`Acct Info` BINARY NOT NULL,
-- 	`Name` BINARY NOT NULL,
-- 	`Client` BINARY NOT NULL,
-- 	PRIMARY KEY (`PK`)
-- );

-- CREATE TABLE `DriverPayment` (
-- 	`PK` BINARY NOT NULL,
-- 	`Acct #` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Current Pay Period` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Total Gross` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Total Net` BINARY NOT NULL AUTO_INCREMENT,
-- 	`Driver` BINARY NOT NULL AUTO_INCREMENT,
-- 	PRIMARY KEY (`PK`)
-- );

-- ALTER TABLE `ClientContact` ADD CONSTRAINT `ClientContact_fk0` FOREIGN KEY (`Billing`) REFERENCES `ClientBilling`(`PK`);

-- ALTER TABLE `DriverContact` ADD CONSTRAINT `DriverContact_fk0` FOREIGN KEY (`Payroll`) REFERENCES `DriverPayment`(`PK`);

-- ALTER TABLE `Rides` ADD CONSTRAINT `Rides_fk0` FOREIGN KEY (`Dispute`) REFERENCES `Disputes`(`PK`);

-- ALTER TABLE `Rides` ADD CONSTRAINT `Rides_fk1` FOREIGN KEY (`Client`) REFERENCES `ClientContact`(`PK`);

-- ALTER TABLE `Rides` ADD CONSTRAINT `Rides_fk2` FOREIGN KEY (`Pool1`) REFERENCES `ClientContact`(`PK`);

-- ALTER TABLE `Rides` ADD CONSTRAINT `Rides_fk3` FOREIGN KEY (`Pool2`) REFERENCES `ClientContact`(`PK`);

-- ALTER TABLE `Rides` ADD CONSTRAINT `Rides_fk4` FOREIGN KEY (`Driver`) REFERENCES `DriverContact`(`PK`);

-- ALTER TABLE `Disputes` ADD CONSTRAINT `Disputes_fk0` FOREIGN KEY (`Ride`) REFERENCES `Rides`(`PK`);

-- ALTER TABLE `Disputes` ADD CONSTRAINT `Disputes_fk1` FOREIGN KEY (`Driver`) REFERENCES `DriverContact`(`PK`);

-- ALTER TABLE `Disputes` ADD CONSTRAINT `Disputes_fk2` FOREIGN KEY (`Client`) REFERENCES `ClientContact`(`PK`);

-- ALTER TABLE `ClientBilling` ADD CONSTRAINT `ClientBilling_fk0` FOREIGN KEY (`Client`) REFERENCES `ClientContact`(`PK`);

-- ALTER TABLE `DriverPayment` ADD CONSTRAINT `DriverPayment_fk0` FOREIGN KEY (`Driver`) REFERENCES `DriverContact`(`PK`);

-- CREATE TABLE IF NOT EXISTS `CLIENT_CONTACT` (
-- 	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
-- 	`name` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`join date` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`phone` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`email` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`username` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`password` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`rating` INTEGER(50) NULL DEFAULT NULL ,
-- 	`blocked` BOOLEAN NULL DEFAULT NULL ,
-- 	PRIMARY KEY (`pk`) ,
-- 	FOREIGN KEY (`billing`) REFERENCES CLIENT_BILLING(`pk`)
-- );


-- CREATE TABLE IF NOT EXISTS `DRIVER_CONTACT` (
-- 	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
-- 	`name` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`join date` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`phone` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`address` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`rating` INTEGER NOT NULL ,
-- 	`email` VARCHAR(50) NULL DEFAULT NULL ,
-- 	 PRIMARY KEY (`pk`) ,
-- 	 FOREIGN KEY (`payroll`) REFERENCES DRIVER_PAYMENT(`pk`)
-- );

-- CREATE TABLE IF NOT EXISTS `RIDES` (
-- 	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
-- 	`date` VARCHAR(50) NULL DEFAULT NULL , 
-- 	`distance` INTEGER NOT NULL ,
-- 	`trip Cost` INTEGER NOT NULL ,
-- 	FOREIGN KEY (`dispute`) REFERENCES DISPUTES(`pk`) ,
-- 	FOREIGN KEY (`client`) REFERENCES CLIENT_CONTACT(`pk`) ,
-- 	FOREIGN KEY (`pool1`) REFERENCES CLIENT_CONTACT(`pk`) ,
-- 	FOREIGN KEY (`pool2`) REFERENCES CLIENT_CONTACT(`pk`) ,
-- 	FOREIGN KEY (`driver`) REFERENCES DRIVER_CONTACT(`pk`)
-- );

-- CREATE TABLE IF NOT EXISTS `DISPUTES` (
-- 	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
-- 	`filing date` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`resolved` BOOLEAN NULL DEFAULT NULL ,
-- 	FOREIGN KEY (`ride`) REFERENCES RIDES(`pk`) ,
-- 	PRIMARY KEY (`pk`)
-- );

-- CREATE TABLE IF NOT EXISTS `CLIENT_BILLING` (
-- 	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
-- 	`address` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`Acct Info` VARCHAR(50) NULL DEFAULT NULL ,
-- 	FOREIGN KEY (`client`) REFERENCES CLIENT_CONTACT(`pk`) ,
-- 	PRIMARY KEY (`pk`)
-- );

-- CREATE TABLE IF NOT EXISTS `DRIVER_PAYMENT` (
-- 	`pk` INTEGER NOT NULL AUTO_INCREMENT ,
-- 	`Acct Info` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`Current Pay Period` VARCHAR(50) NULL DEFAULT NULL ,
-- 	`Total Gross` INTEGER NOT NULL ,
-- 	`Total Net` INTEGER NOT NULL ,
-- 	FOREIGN KEY (`dirver`) REFERENCES DRIVER_CONTACT(`pk`) ,
-- 	PRIMARY KEY (`pk`)
-- );



